apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingester
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ingester
  serviceName: ingester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: ingester
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: loki
                app.kubernetes.io/component: ingester
            topologyKey: kubernetes.io/hostname
      containers:
      - name: ingester
        args:
        - -boltdb.shipper.active-index-directory=/data/index
        - -boltdb.shipper.cache-location=/data/boltdb-cache
        - -config.expand-env
        - -config.file=/etc/loki/config/config.yaml
        - -ingester.wal-dir=/loki/wal
        - -target=ingester
        envFrom:
        - configMapRef:
            name: loki-env-vars
            optional: true
        - secretRef:
            name: loki-env-vars
            optional: true
        image: grafana/loki
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        - containerPort: 7946
          name: memberlist
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 5Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: ingester-data
        - mountPath: /loki/wal
          name: ingester-wal
        - mountPath: /etc/loki/config
          name: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: loki
      terminationGracePeriodSeconds: 4800
      volumes:
      - configMap:
          name: loki
        name: loki
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: ingester-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: ingester-wal
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 150Gi
