apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-frontend
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-frontend
  serviceName: memcached-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: memcached-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: loki
                app.kubernetes.io/component: memcached-frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - name: memcached
        args:
        - -m 1024
        - -I 5m
        - -c 1024
        - -v
        image: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 500m
            memory: 1329Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
      - name: exporter
        args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter
        ports:
        - containerPort: 9150
          name: http-metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 11211
        runAsGroup: 11211
        runAsNonRoot: true
        runAsUser: 11211
  updateStrategy:
    type: RollingUpdate
