apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: loki-ingester-pdb
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ingester
