apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compactor
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: compactor
  endpoints:
  - port: compactor-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: distributor
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: distributor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: distributor
  endpoints:
  - port: distributor-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingester
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ingester
  endpoints:
  - port: ingester-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: querier
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: querier
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: querier
  endpoints:
  - port: querier-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: query-frontend
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: query-frontend
  endpoints:
  - port: query-frontend-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: query-scheduler
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: query-scheduler
  endpoints:
  - port: http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ruler
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ruler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ruler
  endpoints:
  - port: ruler-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-frontend
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-frontend
  endpoints:
  - port: exporter-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-index-queries
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached-index-queries
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-index-queries
  endpoints:
  - port: exporter-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached
  endpoints:
  - port: exporter-http-metrics
