apiVersion: v1
kind: Service
metadata:
  name: ingester
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
spec:
  ports:
  - name: ingester-http-metrics
    port: 3100
    targetPort: 3100
  - name: ingester-grpc
    port: 9095
    targetPort: 9095
  - name: ingester-memberlist
    port: 7946
    targetPort: 7946
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
