apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: memcached
