apiVersion: v1
kind: Service
metadata:
  name: compactor
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
spec:
  ports:
  - name: compactor-http-metrics
    port: 3100
    targetPort: 3100
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
