apiVersion: v1
kind: Service
metadata:
  name: memcached-index-queries
  labels:
    app.kubernetes.io/name: memcached-index-queries
    app.kubernetes.io/part-of: loki
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/name: memcached-index-queries
    app.kubernetes.io/part-of: loki
