apiVersion: v1
kind: Service
metadata:
  name: query-scheduler-discovery
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-scheduler
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    targetPort: 3100
  - name: grpclb
    port: 9095
    targetPort: 9095
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-scheduler
