apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compactor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: compactor
  serviceName: compactor
  template:
    metadata:
      labels:
        name: compactor
    spec:
      containers:
      - name: compactor
        args:
        - -boltdb.shipper.compactor.working-directory=/data/compactor
        - -config.expand-env
        - -config.file=/etc/loki/config/config.yaml
        - -target=compactor
        image: grafana/loki:2.0.0
        ports:
        - containerPort: 3100
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "4"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: compactor-data
        - mountPath: /etc/loki/config
          name: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      volumes:
      - configMap:
          name: loki
        name: loki
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: compactor-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
