apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compactor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: compactor
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: compactor-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: distributor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: distributor
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: distributor-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: ingester-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: querier
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: querier
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: querier-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: query-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: query-frontend
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: query-frontend-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ruler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ruler
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: ruler-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached-frontend
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: exporter-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-index-queries
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached-index-queries
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: exporter-http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: loki
  endpoints:
  - port: exporter-http-metrics
