apiVersion: v1
kind: Service
metadata:
  name: compactor
  labels:
    name: compactor
spec:
  ports:
  - name: compactor-http-metrics
    port: 3100
    targetPort: 3100
  selector:
    name: compactor
