apiVersion: v1
kind: Service
metadata:
  labels:
    name: querier
  name: querier
  namespace: loki
spec:
  ports:
  - name: querier-http-metrics
    port: 3100
    targetPort: 3100
  - name: querier-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: querier
