apiVersion: v1
kind: Service
metadata:
  name: distributor
  labels:
    name: distributor
spec:
  ports:
  - name: distributor-http-metrics
    port: 3100
    targetPort: 3100
  - name: distributor-grpc
    port: 9095
    targetPort: 9095
  - name: distributor-memberlist
    port: 7946
    targetPort: 7946
  selector:
    name: distributor
