apiVersion: v1
kind: Service
metadata:
  name: ingester
  labels:
    name: ingester
spec:
  ports:
  - name: ingester-http-metrics
    port: 3100
    targetPort: 3100
  - name: ingester-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: ingester
