auth_enabled: false
common:
  compactor_address: http://compactor:3100
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached
      service: memcached-client
compactor:
  shared_store: aws
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  scheduler_address: query-scheduler-discovery:9095
  tail_proxy_url: http://querier:3100/
frontend_worker:
  grpc_client_config:
    max_send_msg_size: 104857600
  scheduler_address: query-scheduler-discovery:9095
ingester:
  chunk_idle_period: 15m
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      replication_factor: 3
  wal:
    # should be set upto ~50% of available memory
    replay_memory_ceiling: ${LOKI_INGESTER_WAL_REPLAY_MEMORY_CEILING:-5GB}
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 67108864
  remote_timeout: 1s
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: ${LOKI_LIMITS_CONFIG_INGESTION_BURST_SIZE_MB:-20}
  ingestion_rate_mb: ${LOKI_LIMITS_CONFIG_INGESTION_RATE_MB:-10}
  ingestion_rate_strategy: global
  max_cache_freshness_per_query: 10m
  max_concurrent_tail_requests: ${LOKI_LIMITS_CONFIG_MAX_CONCURRENT_TAIL_REQUESTS:-100}
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 256
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 30m
memberlist:
  join_members:
    - distributor
    - ingester
    - querier
    - ruler
querier:
  engine:
    # Must be a multiple of schema_config index.period
    # Default to 400 days retention.
    max_look_back_period: ${LOKI_QUERIER_ENGINE_MAX_LOOK_BACK_PERIOD:-9600h}
    timeout: ${LOKI_QUERIER_ENGINE_TIMEOUT:-3m}
  query_timeout: ${LOKI_QUERIER_QUERY_TIMEOUT:-60s}
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        host: memcached-frontend
        service: memcached-client
        timeout: 500ms
query_scheduler:
  max_outstanding_requests_per_tenant: 1024
ruler:
  alertmanager_url: ${LOKI_RULER_ALERTMANAGER_URL}
  external_url: ${LOKI_RULER_EXTERNAL_URL}
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
  remote_write:
    enabled: ${LOKI_RULER_REMOTE_WRITE_ENABLED:-false}
    client:
      url: ${LOKI_RULER_REMOTE_WRITE_CLIENT_URL:-""}
  rule_path: /run/loki/ruler/scratch/
  storage:
    type: local
    local:
      directory: /etc/loki/rules
schema_config:
  configs:
    - from: "2020-10-24"
      index:
        period: 24h
        prefix: loki_index_
      object_store: aws
      schema: v11
      store: boltdb-shipper
server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  http_server_write_timeout: 1m
storage_config:
  aws:
    s3: s3:///
    bucketnames: ${LOKI_STORAGE_CONFIG_AWS_BUCKETNAMES}
    sse_encryption: true
  boltdb_shipper:
    shared_store: aws
  index_queries_cache_config:
    memcached:
      batch_size: 100
    memcached_client:
      host: memcached-index-queries
      service: memcached-client
