apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac.yaml
patches:
  - path: ruler.patch.yaml
images:
  - name: kiwigrid/k8s-sidecar
    newTag: 1.15.1
    digest: sha256:a25886092fa4dae9de14825366a1ded3dcfa170c4335e104b7c11830936339c3
