apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac.yaml
patches:
  - path: ruler.patch.yaml
images:
  - name: kiwigrid/k8s-sidecar
    newTag: 1.14.2
    digest: sha256:35654389f8a9b7816193a4811cf3ceb6cf309ece8874e84b3d2d8399e618059b
