{
 "title": "Loki-Canary",
 "description": "Loki Canary is a standalone app that audits the log capturing performance of Loki.",
 "tags": [
  "loki",
  "loki-canary"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total canaries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(loki_canary_entries_total)"
    }
   ]
  },
  {
   "title": "Missing entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_missing_entries_total)"
    }
   ]
  },
  {
   "title": "Total entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_canary_entries_total)" }
   ]
  },
  {
   "title": "Missing Canary Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_missing_entries_total) / sum(loki_canary_entries_total) * 100"
    }
   ]
  },
  {
   "title": "Missing entries rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_canary_missing_entries_total[1m]) / rate(loki_canary_entries_total[1m])) * 100",
     "legendFormat": "Missing entries %"
    },
    {
     "expr": "sum(rate(loki_canary_websocket_missing_entries_total[1m]) / rate(loki_canary_entries_total[1m])) * 100",
     "legendFormat": "WS Missing entries %"
    }
   ]
  },
  {
   "title": "Canary Response Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(loki_canary_response_latency_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Canary Spot Check Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(loki_canary_spot_check_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Loki logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki logs",
     "type": "logs",
     "description": "anything except \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{name=\"loki-canary\"} !=\"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\""
      }
     ]
    }
   ]
  },
  { "title": "Missing entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Websocket reconnects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Websocket reconnects rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_ws_reconnects_total[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Websocket reconnects (top10)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, loki_canary_ws_reconnects_total)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Out of order entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Out of order entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_out_of_order_entries_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Out of order entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_canary_out_of_order_entries_total",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unexpected entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unexpected entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_unexpected_entries_total[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Unexpected entries (top10)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, loki_canary_unexpected_entries_total)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duplicate entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duplicate entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_duplicate_entries_total[5m])) by (job)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Duplicate entries (top10)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, loki_canary_duplicate_entries_total)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total entries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total entries rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_entries_total[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total entries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_entries_total[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average response latency [1m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_canary_response_latency_sum[1m])) / sum(rate(loki_canary_response_latency_count[1m]))",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "Average response latency [1m] per pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(loki_canary_response_latency_sum[1m]) / rate(loki_canary_response_latency_count[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response latency",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "loki_canary_response_latency_bucket"
      }
     ]
    },
    {
     "title": "Response latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "loki_canary_response_latency_bucket"
      }
     ]
    }
   ]
  }
 ]
}