apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
configMapGenerator:
  - name: loki-canary-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - files/dashboard.json
images:
  - name: grafana/loki-canary
    newTag: 2.3.0
    digest: sha256:19922546f8d7a56112d417a9d88ba804ff6334294da201c31c72a705611e9fb7
