apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
images:
  - name: grafana/loki-canary:2.0.0
    digest: sha256:78d83ec294d6d5d8b12fca9bec150ca6325579ca8338ad74b390cdcbbd8475c6
