auth_enabled: false
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached
      service: memcached-client
  # Must be a multiple of schema_config index.period
  # Default to 400 days retention.
  max_look_back_period: 9600h
compactor:
  shared_store: aws
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 200
  tail_proxy_url: querier:3100
frontend_worker:
  frontend_address: query-frontend:9095
  grpc_client_config:
    max_send_msg_size: 104857600
  parallelism: 2
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 15m
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      heartbeat_timeout: 1m
      kvstore:
        store: memberlist
      replication_factor: 3
  max_transfer_retries: 60
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 67108864
  remote_timeout: 1s
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 20
  ingestion_rate_mb: 10
  ingestion_rate_strategy: global
  max_cache_freshness_per_query: 10m
  max_concurrent_tail_requests: 100
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 16
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
    - distributor
    - ingester
    - querier
querier:
  query_ingesters_within: 2h
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: memcached-frontend
        max_idle_conns: 16
        service: memcached-client
        timeout: 500ms
  split_queries_by_interval: 30m
ruler: {}
schema_config:
  configs:
    - from: "2020-10-24"
      index:
        period: 24h
        prefix: loki_index_
      object_store: aws
      schema: v11
      store: boltdb-shipper
server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  http_server_write_timeout: 1m
storage_config:
  aws:
    s3: s3:///${LOKI_STORAGE_CONFIG_AWS_BUCKETNAMES}
    sse_encryption: true
  boltdb_shipper:
    shared_store: aws
  index_queries_cache_config:
    memcached:
      batch_size: 100
    memcached_client:
      consistent_hash: true
      host: memcached-index-queries
      service: memcached-client
