apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - apps-v1.StatefulSet-index-gateway.yaml
  - v1.Service-index-gateway.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: querier
    path: querier-kind.patch.yaml
    options:
      allowKindChange: true
  - target:
      group: apps
      version: v1
      name: querier
    path: server-address.patch.yaml
  - target:
      group: apps
      version: v1
      name: ruler
    path: server-address.patch.yaml
