apiVersion: v1
kind: Service
metadata:
  name: index-gateway
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: index-gateway
spec:
  ports:
  - name: index-gateway-http-metrics
    port: 3100
    targetPort: 3100
  - name: index-gateway-grpc
    port: 9095
    targetPort: 9095
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: index-gateway
